---
title: "Week 2: Satellite Xaringen"
---

```{r echo = FALSE, out.width='40%'}
xaringanExtra::embed_xaringan(
  url = "https://ccciara.github.io/LDXaringen",
  ratio = "16:9")

```

## Reflections

It was very interesting to see the level of spatial and temporal detail that modern satellites are capable of achieving. Weather analysis is obviously very important for climate change studies in the future, but I do wonder what the other uses might be found for satellites like this in the future, particularly more nefarious ones. I've read about other low-orbit satellites - Albedo Space is a recent one - that claim to be capable of identifying individual people, and the images they have provided look pretty convincing. Scary stuff! It does make me wonder where the race for higher and higher resolution is going to end, and what the long term privacy implications are for us on the ground. This also made me curious about the accessibility of the data that these satellites are recording, particularly the ones funded by the government (and thus by the public). How easy is it to get this data for research or non-research purposes, particularly in this high quality?
